major update

diff --git a/build b/build
--- a/build
+++ b/build
@@ -9,8 +9,9 @@
 #   nobuild: do not run cmake generation or make
 #   copy: copies bin/plugin.3gx to citra (environment var CITRA_DATA must be set to citra's data folder)
 #   run-nogui: runs mariokart7 from citra.exe (environment var CITRA must be set to citra.exe's path)
-#   run-qt: runs mariokart7 from citra.exe (environment var CITRA_QT must be set to citra-qt.exe's path)
+#   run-qt: runs mariokart7 from citra-qt.exe (environment var CITRA_QT must be set to citra-qt.exe's path)
 
+make_ret=0
 Reset='\033[0m'           # Text Reset
 Black='\033[0;30m'        # Black
 Red='\033[0;31m'          # Red
@@ -35,25 +36,36 @@ if [[ "$*" != *"nobuild"* ]]; then
 	 ../../CMakeLists.txt
 	 
 	make --always-make
+	make_ret=$?
 fi
 
 cd ../../
 
+if [ $make_ret -ne 0 ]; then
+	echo -e "${Red}Last build failed.${Reset}" 
+	exit
+fi
+
 # Create .3gx from built elf file
-${DEVKITARM}/bin/3gxtool.exe -s bin/ctr-plugin.elf settings.plgInfo bin/ctr-plugin.3gx
+if [ $make_ret -eq 0 ]; then
+	${DEVKITPRO}/tools/bin/3gxtool.exe -s bin/ctr-plugin.elf settings.plgInfo bin/ctr-plugin.3gx
+fi	
+
 if [[ "$*" = *"copy"* ]]; then
 	#copy plugin to citra's luma plugin path
 	if [[ -z "${CITRA_DATA}" ]]; then
 		echo -e "${Cyan}Please specify a citra appdata path, otherwise define the environment variable CITRA_DATA with the necessary path\033[0m"
 		read ctrdata
-		cp bin/ctr-plugin.3gx $ctrdata/sdmc/luma/plugins/0004000000030800/ -i
+		cp -rf bin/ctr-plugin.3gx $ctrdata/sdmc/luma/plugins/0004000000030800/
 	else
-		cp bin/ctr-plugin.3gx ${CITRA_DATA}/sdmc/luma/plugins/0004000000030800/ -i
+		cp -rf bin/ctr-plugin.3gx ${CITRA_DATA}/sdmc/luma/plugins/0004000000030800/
 	fi
 fi
 
-if [[ "$*" = *"run-nogui"* ]]; then
-	echo -e "${Blue}Launching citra..."
+if [[ "$*" = *"run-headless"* ]]; then
+	echo -e "${Blue}Launching citra...${Reset}"
+	
+	
 	# run citra.exe with mk7
 	#
 	# in order for the plugin to actually run from citra.exe, you must set plugin-loader to true in ${CITRA_DATA}/config/sdl2-config.ini
@@ -73,7 +85,8 @@ if [[ "$*" = *"run-nogui"* ]]; then
 fi
 
 if [[ "$*" = *"run-qt"* ]]; then
-	echo -e "${Blue}Launching citra-qt..."
+	echo -e "${Blue}Launching citra-qt...${Reset}"
+	
 	# run citra-qt.exe with mk7
 	#
 	# Luma3GX plugin loading must be enabled in the settings in order for the plugin to load
